### ISSUE TITLE
SECTION_PAGE_URL в выборке SectionModel

### ISSUE THREAD

**Issue by ProklUng** [arrilot/bitrix-models#10]
Выдает шаблон ссылок, а не уже сгенерированные ссылки (как понимаю из-за применения fetch вместо GetNext)

 $sectionsListForSmallMenu = oboiCollection::query()->select('ID')
	                ->sort(["SORT" => "ASC", "NAME" => "ASC"])
					->filter(["IBLOCK_ID" => $arParams['IBLOCK_ID'], "ACTIVE" => "Y", "SECTION_ID" => false])
	                ->limit(10)
	                ->select("ID", "CODE", "NAME", "SECTION_PAGE_URL")
	                ->getList()
	                ->toArray()
	;

    printr ($sectionsListForSmallMenu);

Результат:

[4550] => Array
        (
           
            [SECTION_PAGE_URL] => #SITE_DIR#wallcoverings/#SECTION_CODE_PATH#/
       )

**Comment by arrilot** [comment]
Это та же проблема что и в предыдущей issue.  Нужен способ настраивать как именно получается выборка, через fetch(), GetNext() или GetNextElement().
Эту закрываю, ту оставляю открыйто
