### ISSUE TITLE
События для Eloquent моделей

### ISSUE THREAD

**Issue by vkryukov76** [arrilot/bitrix-models#13]
Нужна возможность "подписки" на события Eloquent-моделей
https://laravel.com/docs/5.5/eloquent#events

Если для стандартных сущностей такая возможность предоставляется из Битрикс API.
То при использовании Eloquent моделей этого очень не хватает.

**Comment by arrilot** [comment]
А ты пробовал сделать как в документации описано?
```php
   protected $dispatchesEvents = [
        'saved' => UserSaved::class,
        'deleted' => UserDeleted::class,
    ];
```

Я вообще думал что это нормально работает как и всё остальное в Eloquent :)

**Comment by vkryukov76** [comment]
"Из коробки" не заработало. В том числе после установки `illuminate/events`.

**Comment by vkryukov76** [comment]
Апдейт

Будет работать, если установить `illuminate/events` и  в `ServiceProvider` в метод `bootstrapIlluminateDatabase` добавить:

```php
$dispatcher = new Illuminate\Events\Dispatcher();
$capsule->setEventDispatcher($dispatcher);
```

**Comment by arrilot** [comment]
Ага, спс.

Добавил в новом релизе.
https://github.com/arrilot/bitrix-models/commit/d06b83ed03060ba51a1ea04d7d228f1de0c793c8
