### ISSUE TITLE
Флаг bWorkFlow для создания/обновления элемента инфоблока

### ISSUE THREAD

**Issue by dvcarrot** [arrilot/bitrix-models#24]
https://dev.1c-bitrix.ru/api_help/iblock/classes/ciblockelement/add.php
https://dev.1c-bitrix.ru/api_help/iblock/classes/ciblockelement/update.php

добавьте пожалуйста поддержку флага `bWorkflow`, также как это сделано для флага `bUpdateSearch`

**Comment by arrilot** [comment]
Реализовано в 0.7.12
