### ISSUE TITLE
Как сделать группировку в d7Model для хайлоадблоков?

### ISSUE THREAD

**Issue by americanidiot** [arrilot/bitrix-models#25]
Предполагаеться что в результате должно вернуть кол-во, но не вернуло...

**Comment by arrilot** [comment]
Привет, покажи код плиз

**Comment by americanidiot** [comment]
class LikeCounter extends D7Model{

    public static function tableClass(){

        $hlBlock = HighloadBlockTable::getList(
            array(
                'filter' => array(
                    'TABLE_NAME' => 'it_like_counter'
                )
            )
        )->fetch();

        return HighloadBlockTable::compileEntity( $hlBlock )->getDataClass();
    }
}
Правда функции group нету, ну я ее дописал по аналогии с filter
$resLike = LikeCounter::query()->filter(array('UF_ID' => $arResult['IDS']))->group(array('UF_ID'))->select(array('CNT', 'UF_ID'))->getList();

что такое пробовал, но всеравно не понял как агреггирующие функции юзать и групировать

**Comment by arrilot** [comment]
Такое ощущение, что Битрикс просто игнорирует параметр 'group' для хайлоадблока в подобном вызове (взято из документации)

```
BookTable::getList(array(
    'group' => array('PUBLISH_DATE')
));
```
Пакет именно к такому виду всё приводит.
