### ISSUE TITLE
Без подключения модуля iblock выдает ошибку

### ISSUE THREAD

**Issue by ibadin** [arrilot/bitrix-models#31]
Без подключения модуля iblock выдает ошибку "Object initialization failed"

**Comment by arrilot** [comment]
Пакет ожидает что этот модуль всегда подключен. Лично мы включаем его в init.php для всего проекта сразу - меньше проблем потом

**Comment by ibadin** [comment]
Также сделал, думаю в доку неплохо было бы добавить
