### ISSUE TITLE
Детальная настройка подключения к БД

### ISSUE THREAD

**Issue by maltf0** [arrilot/bitrix-models#33]
Здравствуйте!

Можно-ли, не модифицируя **bitrix-models**, организовать работу с несколькими БД?
Например, добавить внешнюю БД **postgree**.

Стандартно в Битриксе это решается добавлением подключения в файле _/bitrix/.settings.php_

Второй вопрос: можно-ли в **bitrix-models** добавлять **options** для подключения?
Пример из Laravel: 
_app/config/database.php_
```
return array(
    'connections' => array(
        'mysql' => array(
            'options'   => array(
                PDO::ATTR_CASE => PDO::CASE_UPPER,
            ),
        ),
     )
)
```

Это позволит объявлять в моделях названия колонок таблиц в **lower_case**.

**Comment by arrilot** [comment]
Привет, Eloquent конфигурируется по данным дефолтного подключения к БД из битриксового конфига https://github.com/arrilot/bitrix-models/blob/master/src/ServiceProvider.php#L84
Теоретически я вижу что это можно доработать - добавить проверку на наличие в битриксовом конфигемассива bitrix-models.illuminate-database. Внутри этого массива ключи default и connection в формате как здесь https://github.com/laravel/laravel/blob/master/config/database.php
Если этого конфига не задано, то использовать текущую логику для обратной совместимости и удобства в простых кейсах.

Готов смержить подобный PR если кто-то заинтересован в том чтобы его сделать.

**Comment by maltf0** [comment]
Наконец-то руки дошли https://github.com/arrilot/bitrix-models/pull/34
