### ISSUE TITLE
In development?

### ISSUE THREAD

**Issue by vkryukov76** [arrilot/bitrix-models#4]
Использовал модуль на небольшом проекте. Показалось что он довольно стабильный, но напрягает надпись "В разработке".

Вижу что уже год не было по нему обновлений. Хотелось бы узнать что осталось нереализованным, какие могут быть подводные камни при использовании?

**Comment by arrilot** [comment]
Да, 0.4 действительно очень стабильна на php 5.5.
На 7.0 не проверял.
Я планирую в ближайшее время немного оживить проект.
Скорее всего где-то через месяц будет версия 0.5 которая будет требовать php7.0 и будет уметь работать еще и с пользовательскими таблицами/hlблоками
