### ISSUE TITLE
Использование пакета в рамках laravel 5.4

### ISSUE THREAD

**Issue by oleg-vysotsky** [arrilot/bitrix-models#6]
Было бы удобно использовать этот пакет для самого laravel 5.4, при использовании laravel в качестве фронта.

В данный момент выбрасывает ошибку:

FatalThrowableError in ProviderRepository.php line 149:
Call to undefined method Arrilot\BitrixModels\ServiceProvider::isDeferred()

**Comment by arrilot** [comment]
Это пакет для Битрикса и сервис провайдер соответственно для него а не для Laravel.
Можешь попробовать зарегистрировать его где-нибудь в бутстрапе или в middleware, но вообще такое использование никак не поддерживается.
Планов внедрять такое тоже нет.
