### ISSUE TITLE
Еще один момент: выборка множественного поля типа список | Ошибка 

### ISSUE THREAD

**Issue by ProklUng** [arrilot/bitrix-models#9]
Выборка множественного поля типа список, вываливается: 

Fatal error: [] operator not supported for strings in [..]./vendor/arrilot/bitrix-models/src/Queries/BaseQuery.php on line 377 

Если поле пустое, то всё OK.

**Comment by arrilot** [comment]
Напиши пожалуйста:
1. Версию инфоблока (1 или 2)
2. Пример кода (Model::query()->....) который приводит к ошибке
3. Какие значения у списка есть и сколько (можно скрин)

**Comment by ProklUng** [comment]
1. 1.0.
2. 

$products = oboi::query()->select('ID')
		->sort(['SORT' =>'DESC'])
		->select ('NAME', 'FIELDS',
				'PROPERTY_PRODUCER', 'PROPERTY_SELLFORM',
            	'PROPERTY_SOSTAV', 'PROPERTY_WIDTH',
				'PROPERTY_LENGTH', 'PROPERTY_RAPORT',
            	'PROPERTY_ROOL', 'PROPERTY_PHOTO',
            	'PROPERTY_PDF', 'PROPERTY_PATTERNSHIFT',
            	'PROPERTY_WHOLEPIC', 'PROPERTY_COUNTRY',
            	'PROPERTY_WEIGHT', 'PROPERTY_EXAMPLE',
            	'PROPERTY_OBOIANALOG', 'PROPERTY_MATERIAL',
            	'PROPERTY_STIL', "PROPERTY_SPCL", "PROPERTY_DLVRTM",
            	"PROPERTY_CVET", 'PROPERTY_FITCHES'

				)

		->getList()
        ->toArray();

Обламывается только на PROPERTY_FITCHES (и то если оно не пустое). Множественный список:

![screenshot_1](https://user-images.githubusercontent.com/19857467/31226406-a676ad32-a9de-11e7-9988-17f1b480d156.jpg)

**Comment by arrilot** [comment]
Исправлено в 0.5.4
